### ISSUE TITLE
How to use pipeline with: DEBUG=TRUE and PIPELINE_ENABLED: True

### ISSUE THREAD

**Issue by sowinski** [jazzband/django-pipeline#577] opened 2016-06-30 08:12 UTC
Hi,

pipeline is doing a good job, but I would like to enable pipeline while I am developing.
If I turn DEBUG=True und PIPELINE_ENABLED = True I can not access my static_files.

**Comment by devsnd** [comment] 2016-07-06 07:18
I am currently seeing the same issue. This seems to be a duplicate of #487 however.

**Comment by devsnd** [comment] 2016-07-06 07:44
BTW: I have implemented a simple workaround for this issue, see #487 for details.

**Comment by bashu** [comment] 2016-07-11 07:38
same issue

**Comment by Flimm** [comment] 2017-05-24 16:13
@sowinski This looks like it's a duplicate of #487.

**Closed by Flimm** 2017-05-24 16:13 UTC
