### ISSUE TITLE
collect static error with custom django-storages

### ISSUE THREAD

**Issue by dhararon** [jazzband/django-pipeline#574] opened 2016-06-27 18:38 UTC
Hi,
i read similar issues but i can't do work django-pipeline + django-storages

this is my custom class:

```python
from django.contrib.staticfiles.storage import CachedFilesMixin

from pipeline.storage import PipelineMixin

from storages.backends.s3boto import S3BotoStorage

class S3PipelineCachedStorage(PipelineMixin, CachedFilesMixin, S3BotoStorage):
	pass
```

and this is my settings:

```python
STATICFILES_STORAGE = 'app.storages.S3PipelineCachedStorage'
```

and my version libraries are:

- django-pipeline==1.6.8
- django-storages==1.4.1
- boto==2.40.0

and when i run 
```python
./manage.py collectstatic
 ```
return this error

```python
from storages.backends.s3boto import S3BotoStorage
ImportError: No module named backends.s3boto
```

**Comment by cyberdelia** [comment] 2016-06-27 19:17
It looks like you have a import conflict between ``app.storages`` and ``storages``.

Closing as this is not a bug due to django-pipeline.

**Closed by cyberdelia** 2016-06-27 19:17 UTC
